### ISSUE TITLE
wifi能连吗

### ISSUE THREAD

**Issue by zch6348135** [leeboby/armbian-images#2]
固件用的是debian12 server
使用nmcli dev wifi指令可以扫描到ssid,连接后提示Connection activation failed: The Wi-Fi network could not be found.
重复两次操作后扫描不到ssid

**Comment by leeboby** [comment]
加sudo试下

**Comment by ix-prism** [comment]
和你一样，armbian-config连接提示未找到ssid，两次后扫不到ssid
更换debian后正常
